### ISSUE TITLE
Copying to clipboard breaks

### ISSUE THREAD

**Issue by lazarljubenovic** [weareneopix/daily-log#9]
On Ubuntu 17.04, the output displays properly and then instead of a message for successful copy to clipboard, the following appears.

```
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOTDIR
    at exports._errnoException (util.js:1028:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:387:9)
    at Object.exports.copy (/usr/local/lib/node_modules/@weareneopix/daily-log/node_modules/copy-paste/index.js:43:14)
    at git.raw (/usr/local/lib/node_modules/@weareneopix/daily-log/index.js:51:8)
    at Git.<anonymous> (/usr/local/lib/node_modules/@weareneopix/daily-log/node_modules/simple-git/src/git.js:607:18)
    at Git.<anonymous> (/usr/local/lib/node_modules/@weareneopix/daily-log/node_modules/simple-git/src/git.js:1305:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
```

**Comment by lazarljubenovic** [comment]
On Ubuntu 18.04, I just get a clean error: `Copying to clipboard was not successful.`. Could be related to this so posting it here.

**Comment by lazarljubenovic** [comment]
From [the `copy-paste` docs](https://www.npmjs.com/package/copy-paste) (emphasis mine):

> A command line utility that allows read/write (i.e copy/paste) access to the system clipboard. It does this by wrapping `pbcopy`/`pbpaste` (for OSX), **`xclip` (for Linux and OpenBSD)**, and `clip` (for Windows). Currently works with node.js v0.8+.

Trying to run `xclip` on my Ubuntu, I get this:

```
Command 'xclip' not found, but can be installed with:

sudo apt install xclip
```

After running the suggested command and re-running `git daily-log`, everything works as expected.

---

So I guess we should inspect the error returned by the `copy-paste` package and provide the necessary instructions on our own.
